### ISSUE TITLE
DW-PBJ9-Kimberly

### ISSUE THREAD

**Issue by heathkn** [gmhhope/fall-postbacc-journal-club-2022#124]
# Discussion worksheet

## Multiple early factors anticipate post-acute COVID-19 sequelae

----------------------
## Main Research Question and Contribution to the fields?
The researchers aimed to determine predictive risk factors of post-acute sequalae of COVID-19 (PASC).

----------------------
## Methods & Data
The data presented supports that there are predictive risk factors for PASC. Among these are included varying levels of biomarkers (e.g. deficient cortisol levels, increased protein levels involved in the circadian rhythm), reactivation of Epstein-Barr Virus (EBV), and associations between gastrointestinal PASC and unique T cell clonal dynamics, all contributing to the development of PASC. The figures go to demonstrate the claims made by the authors, reinforcing these conclusions. One finding I found surprising was the significant connection between autoAbs, T2 hyperinflammation and T3 PASC; I did not expect they would find such an evident relationship that would directly tie into PASC.

----------------------
## Authors' interpretation
I agree with the authors' interpretation of the data. See above.

----------------------
## Enhancement or next experiment?
This study could be enhanced by having continued through long-term follow-up (for example 6 months after initial infection) to determine risk factors of long-term chronic PASC.

----------------------
## confusion? Terms you don't understand?
Why were they not able to preserve granulocytes in their blood sample processing?

----------------------
## Have your own opinions or critiques
The sample cohorts are heavily skewed toward white individuals. From a public health perspective, this could also be confounding data as it is known that minority/underserved populations have a higher risk of developing worse disease outcomes due to access to healthcare and resources in general.

-----------------------
**I hereby confirm that I have:**
- [ ] I am still working on the worksheet
- [X] I have finished the worksheet
- [X] I have gone through the papers
- [X] Check your peer if they have similar ideas. If it is, plz add their issue number to your comments.

**Comment by gmhhope** [comment]
> Why were they not able to preserve granulocytes in their blood sample processing?
Not sure either.
