### ISSUE TITLE
DW-PBJ2-Harsha

### ISSUE THREAD

**Issue by gmhhope** [gmhhope/fall-postbacc-journal-club-2022#37]
### Discussed in https://github.com/gmhhope/fall-postbacc-journal-club-2022/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **Harsha-Tamtam** October  3, 2022</sup>
## Main Research Question

The authors of this paper aimed to determine how the SARS-CoV-2 virus triggers the inflammatory response. After looking at blood samples, the authors found that leukocytes (monocytes) display inflammasomes that trigger pyroptosis. Specifically, the inflammasomes detect the CoV-2 antigen (opsonized then taken in through endocytosis)) via the CD16 Ig-receptor. The result of this is an immediate prevention of viral replication, but consequently, a rampant cytokine storm that exacerbates SARS-CoV-2 symptoms.

----------------------
#### Methods
- The authors utilize ELIZA to observe titer levels and antigen-antibody recognition thresholds, providing a quantifiable measure of Ig and inflammatory response. 
- Flow cytometry counts the cells via stains that characterize their physical alterations under infection. 
- Microscopy provides color-coded differentiation for various signals and cellular organization. 
- Immunoblot and RNA-seq quantified protein-protein interactions and viral replication, respectively, in monocytes.

#### Data
- The data presented matches the author's reasonings and conclusions. Having an undergraduate background in biology, I was able to understand the images at a baseline level and follow the interpretations the author's described for each image. The subfigures provided detailed information that confirmed the subsequent experiment and posited other considerations to be addressed.

----------------------
## Authors' interpretation

The interpretations were somewhat difficult to follow, but after reading through some prior papers, I was able to understand some sections that eluded me. Reading papers such at this requires some background knowledge that the author (understandably) assumed the audience would have. Given this, the following interpretations were not difficult to extrapolate from the data. However, if the data were to stand alone, I would see some difficulty arriving to the same conclusions the authors came to. This is likely because I am not familiar with these topics, and this opinion may fade after reading more papers of this type.

----------------------
## Enhancements/Possible experiments?

See my [comment](https://github.com/gmhhope/fall-postbacc-journal-club-2022/issues/37#issuecomment-1266953882). Additionally, although the authors mentioned there were no IFNs detected above baseline, I would have liked to see the figure demonstrating that was the case(pg.578, right side). 

----------------------
## Any confusion in the literature?

- I understand that measuring GSDMD levels is a good indicator of pyroptosis. However, from the article (pg.580, right side), why would they still choose the measure GSDMD when there was no significant difference(s) between severe and mild/moderate patient serum samples in COV-2 infected patients (Fig. 1h)?
 
- **No others as of now**

----------------------
## Opinions/Critiques?

Measuring rates of sodium/potassium influx/efflux would have solidified that pyroptosis is occurring, as this does not happen in apoptosis. However, I can see this being difficult, as the GSDMD is creating pores that destabilizes the cell membrane. Creating an environment that determine rates of ioinic flow (a variation of neuronal cell patch clamping) could fit this experiment.

-----------------------
**I hereby confirm that I have:**
- [x] I have gone through the papers
- [x] I am still working on the worksheet
- [x] I have finished the worksheet
- [ ] Check your peer if they have similar ideas. If it is, plz add their issue number to your comments. 

</div>

**Comment by gmhhope** [comment]
I am going to modify yours to create a better reading experience. See my edit and learn some markdown features.

**Comment by gmhhope** [comment]
## measure Na/K+ in/efflux?

> Measuring rates of sodium/potassium influx/efflux would have solidified that pyroptosis is occurring . . .
- This is an interesting experiment to propose. I haven't done any measuring though and if you wish, please also include specifics techniques you would like to refer with link to the methods/kits. 
- However, practically, for immunological studies, cells are usually very **fragile**, especially for myeloid cells. Not to mention, you need to infect them with virus or analyzing patients' monocytes (probably very inflammatory already). So usually immunologists try to perform the less harsh experiment. Human monocytes are not cell lines so they cannot easily reproduce unless using current technology like iPSC-derived monocytes. **Cell numbers** will be a big limitation for a lot of experiments.
- For peer review, as long as 1-2 experiment clearly prove the process and convince the reviewers of the conclusion, we, the reviewer avoids proposing another experiment to prove the same conclusion with another angle unless it may imply further explanations to the results.

## GSDMD measurement
> pg.580, right side),
- cannot find that, try to indicate them using 
   - > quoted sentence...

> why would they still choose the measure GSDMD when there was no significant difference(s) between severe and mild/moderate patient serum samples in COV-2 infected patients (Fig. 1h)?
- Suggestion: link your figure (remember drag & drop) 
![IMG_F7E3041EB767-1](https://user-images.githubusercontent.com/12982817/193712008-7104a4f1-f5e7-4cec-a06c-c5357c2cef68.jpeg)

- GSDMD is a critical & unique molecule that symbolizes pyroptosis (Check [our discussion](https://github.com/gmhhope/fall-postbacc-journal-club-2022/discussions/35)). You cannot avoid showing it, especially in this Nature-standard publication. Significance `p < 0.05` doesn't dictate everything. But the trend is there. They also further prove the conclusions in later figures, solidifying the results.
- But this is a very good observation! Yes, that can actually be a weakness for this paper I guess 👍

**Comment by Harsha-Tamtam** [comment]
I completely understand your reasoning behind measuring influx/efflux of conducting ions and the continued use for GSDMD measurements. I did find a paper ([here](https://www.nature.com/articles/cddiscovery201770)) by DiPeso et. al., in which the mitochondrial membrane potential was measured to confirm GSDMD pore formation via TMRM fluorescence. An interesting experiment that could add to this paper.
<img width="593" alt="Screen Shot 2022-10-04 at 8 58 13 AM" src="https://user-images.githubusercontent.com/113044010/193825560-42fd9f9d-275b-4461-874b-45a1504d9891.png">

**Comment by gmhhope** [comment]
Good idea! MMP measurement is a good indicator of dysfunctional mitochondrial activity. However, the disadvantage is that MMP measurement is also frequently used for identifying apoptosis. Thus, it cannot distinguish pyroptosis from apoptosis. 
![apoptosis](https://ars.els-cdn.com/content/image/1-s2.0-S002228362100615X-gr2_lrg.jpg)

**Comment by gmhhope** [comment]
I even don't know the fact that you can link your comment as a link. An excellent way to make things readable! 

Thanks and this is how I learn from you guys : )

**Comment by gmhhope** [comment]
## Typical style of Nature Letter
> Given this, the following interpretations were not difficult to extrapolate from the data. However, if the data were to stand alone, I would see some difficulty arriving to the same conclusions the authors came to. This is likely because I am not familiar with these topics, and this opinion may fade after reading more papers of this type.

I am sorry that you will gradually realize this is a typical style of big paper. Not everything is already there in the paper. I hope I have touched on all your points. Let me know if you still have more. 

I found one annoying thing is that I cannot easily find your tracked changes so I need to keep re-read your comments. This is an unfortunate fact but let me know if I haven't touched on sth. you are eager to know : )
