### ISSUE TITLE
DW-PBJ2-Megan Costa

### ISSUE THREAD

**Issue by megancosta04** [gmhhope/fall-postbacc-journal-club-2022#39]
## Main Research Question?
The authors of the paper aimed to investigate the immunological sequelae that is activated post-COVID infection. Namely, what are the main biochemical agents involved and what are their functions?

----------------------
## Methods & Data
Examination of Patient Blood (19 HDs/22 Patients)/Cell Marker Staining/Monocyte Flow Cytometry:
•	Markers specific to pyroptosis and general inflammation markers were significantly elevated in the blood of COVID-19
•	Pyroptosis biomarkers correlated with severity of the disease

qPCR/RT-qPCR: 
•	10% of patient-derived monocytes stained for N or dsRNA, 95% were positive for J2, almost all were positive for ASC specks

Infection of HD monocytes/Flow Cytometry:
•	Blocking two of the three monocyte FcγRs (CD16/CD64) strongly inhibited infection

----------------------
## Authors' interpretation
I agree with the author’s interpretation, but I had to read through several times to understand their rationale. This is a very different field than cancer research, so there was a huge learning curve initially.

----------------------
## Enhancement or next experiment?
It may be interesting to expand the study to other hospitals around the country and link demographic data (i.e., race, age, socioeconomic status) to differences in inflammation. Also, while COVID-19 is primarily a disease of the lungs, investigating inflammation in other organs such as the heart would be fascinating.

----------------------
## confusion? Terms you don't understand?
I had to look up the definition of “pyroptosis” and remind myself of each of the biomarkers and their significance as I was going through the paper.

----------------------
## Have your own opinions or critiques
I enjoyed the paper and thought the figures were nicely organized and easy to follow. I wish there were better annotations in the figures, personally, as I found myself confusing biomarker names and abbreviations. Perhaps that’s because I’m not as familiar with immunology.

-----------------------
**I hereby confirm that I have:**
- [ ] I am still working on the worksheet
- [X] I have finished the worksheet
- [X] I have gone through the papers
- [X] Check your peer if they have similar ideas. If it is, plz add their issue number to your comments.

**Comment by gmhhope** [comment]
### Try to be specific on Main Research Question
> The authors of the paper aimed to investigate the immunological sequelae that are activated post-COVID infection. Namely, what are the main biochemical agents involved and what are their functions?

Good that you foresaw the hints at [PASC](https://www.yalemedicine.org/conditions/long-covid-post-acute-sequelae-of-sars-cov-2-infection-pasc). But for summary, this runs a little bit too far. "Sequelae" is more about post-COVID infection while in this study, the infection is current. So be careful of the terms you use (just imagine you are writing your first summary for peer review of this paper). 

----------------------
### Immunologist likes to confuse others with all sorts of abbreviated markers
> I enjoyed the paper and thought the figures were nicely organized and easy to follow. I wish there were better annotations in the figures, personally, as I found myself confusing biomarker names and abbreviations. Perhaps that’s because I’m not as familiar with immunology.

- Yes, Immunology tends to confuse others with `CD#` with a long history behind it but not explicitly telling why.
- So welcome to the field of Immunology!

---------------------
### COVID-19 and metabolic disease are tightly linked
> It may be interesting to expand the study to other hospitals around the country and link demographic data (i.e., race, age, socioeconomic status) to differences in inflammation. Also, while COVID-19 is primarily a disease of the lungs, investigating inflammation in other organs such as the heart would be fascinating.

Good you have noticed this trend of future COVID-19 research. Join discussion when [PBJ-7](https://github.com/gmhhope/fall-postbacc-journal-club-2022/wiki/PBJ7) arrives

----------------------
### Pyroptosis and previous discussion 
> I had to look up the definition of “pyroptosis” and remind myself of each of the biomarkers and their significance as I was going through the paper. 

See #37 and discussion on the different [fates of cell death](https://github.com/gmhhope/fall-postbacc-journal-club-2022/discussions/35)
