### ISSUE TITLE
DW-PBJ2-Rei Bufi

### ISSUE THREAD

**Issue by reibufi** [gmhhope/fall-postbacc-journal-club-2022#57]
# Discussion worksheet

----------------------
## Main Research Question?
*In your own words, provide a brief description of the main research question being pursued in this paper.*

The main research question being pursued in this paper is the effects of the SARS-CoV-2 virus has on triggering the inflammatory response.

----------------------
## Methods & Data
*Consider the methods used and the data presented. Do the data support the hypothesis/research question? Explain why or why not. Were there any unexpected results?*

The authors used numerous assays (i.e. ELISA, flow cytometry, immunoblot RNA-seq, etc) to quantify and determine the relationship between inflammatory markers and SARS-CoV-2 infection. The methods used are appropriate and do indeed provide enough data and evidence to answer the research question. 

----------------------
## Authors' interpretation
*Do you agree with the authors’ interpretation of the data? Why or why not?*

I agree with the authors' interpretation of the data. Their results are also supported by previous findings in the literature.

----------------------
## Enhancement or next experiment?
*What do you think the authors should do next?*

I think it would be interesting to see the level of inflammation at a systematic level and/or long-term effects of the inflammation response.

----------------------
## confusion? Terms you don't understand?
*What are your areas of confusion as you analyze this paper?  Are there terms that you don’t understand? What questions do you have about the research aim, methods, or data?*

The paper itself was dense and it took me some time to decipher. 

----------------------
## Have your own opinions or critiques
***Pretend you are a reviewer** and come up with one critique of the paper (e.g., something the authors could have done better, or an experiment that would strengthen the paper).*

I think it would have been interesting if after infection, the authors could have blocked the virus from replicating, and then see if the inflammatory response would return back to baseline. I am not sure if this is something that would logistically make sense for this study specifically (I come from a genetics background and this approach is done often).

-----------------------
**I hereby confirm that I have:**
- [ ] I am still working on the worksheet
- [x] I have finished the worksheet
- [x] I have gone through the papers
- [x] Check your peer if they have similar ideas. If it is, plz add their issue number to your comments.

**Comment by gmhhope** [comment]
> I think it would have been interesting if after infection, the authors could have blocked the virus from replicating, and then see if the inflammatory response would return back to baseline. I am not sure if this is something that would logistically make sense for this study specifically (I come from a genetics background and this approach is done often).

Excellent point! Indeed, I think the [Richard Flavell's paper](https://www.nature.com/articles/s41586-022-04802-1) addressed your question more appropriately. I think the short answer is "YES". 
- [Extended Data Fig. 14 Promoting or blocking viral entry or replication in human macrophages in vivo and in vitro impacts inflammatory profile of macrophages (matched to figure ](https://www.nature.com/articles/s41586-022-04802-1/figures/18)[3](https://www.nature.com/articles/s41586-022-04802-1#Fig3)).

But they addressed this more in a systematic way not particular in context of monocyte infection of SARS-CoV2. That will be a good experiment to compensate the results.


> I think it would be interesting to see the level of inflammation at a systematic level and/or long-term effects 

- These are more answered appropriately in the 2nd paper. You are on a right track!
