### ISSUE TITLE
DW-PBJ3-Rei

### ISSUE THREAD

**Issue by reibufi** [gmhhope/fall-postbacc-journal-club-2022#72]
# Discussion worksheet

----------------------
## Main Research Question?

The paper seeks to shed light into the immune response against reinfection with SARS-Cov-2.

----------------------
## Methods & Data

Human samples were used to measure proteins of interest through ELISA. Sorting was done by using flow cytometry.

----------------------
## Authors' interpretation

The authors say that the changes in the anti-RBD have a significance of P<0.0001, however looking at the figure 1c with the number of the values, I am not fully convinced there is a significant difference between the two. @gmhhope which figures are you talking about?

----------------------
## Enhancement or next experiment?

It would be interesting to see if they could replicate the findings with people who have received the vaccine.

----------------------
## confusion? Terms you don't understand?

I was a bit confused about what each antibody does in terms of healthy bodily function in the bigger picture. Like what do the changes in the various antibodies lead to physiologically? @Harsha-Tamtam @paige-ramkissoon Could you guys try to cover this part in your presentation?

----------------------
## Have your own opinions or critiques

The samples were collected from individuals 18-76 years old. Immune responses have great variability as people get older. How do we know that the changes that we are seeing in the different antibodies are due to the SARS-Cov-2 and not from differences in age? @gmhhope see my comments

-----------------------
**I hereby confirm that I have:**
- [ ] I am still working on the worksheet
- [x] I have finished the worksheet
- [x] I have gone through the papers
- [x] Check your peer if they have similar ideas. If it is, plz add their issue number to your comments.

**Comment by gmhhope** [comment]
> The samples were collected from individuals 18-76 years old. Immune responses have great variability as people get older. How do we know that the changes that we are seeing in the different antibodies are due to the SARS-Cov-2 and not from differences in age?

Since the comparison is between time points across individuals, the age effect is canceled out. However, age does play a significant role in Ig pools. So this can be the next question they need to address.
